### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by drewfreyling** [GlobalX/GlobalX.ChatBots.Core#3]

**Comment by drewfreyling** [comment]
Are we happy with GPLv3 just like pockybot?

**Comment by Lauraducky** [comment]
The funny thing is that PockyBot has ISC listed in its package.json (presumably by Jonathan back when he created it). Personally I would prefer a more permissive license such as Apache or MIT but that's just my preference.

**Comment by Chromadream** [comment]
Personally, I would prefer a more permissive license too, but if we're going with GPL family, LGPL would make more sense for a library.

**Comment by drewfreyling** [comment]
> The funny thing is that PockyBot has ISC listed in its package.json (presumably by Jonathan back when he created it). Personally I would prefer a more permissive license such as Apache or MIT but that's just my preference.

Looks like you added GPLv3 to the repo? https://github.com/GlobalX/pockybot/blob/master/LICENSE

**Comment by jimcullenaus** [comment]
I have no strong preference on license.

@drewfreyling this issue is around the GlobalX.ChatBots.Core, not pockybot.

**Comment by Lauraducky** [comment]
@drewfreyling I did but only because it was there on the original pockybot project (I think Jim added it)

**Comment by Evangelinexx** [comment]
My vote is for a more open license such as MIT or ISC

**Comment by drewfreyling** [comment]
everyone happy with MIT then?
